import { useEffect, useMemo, useState } from 'react'
import { addDoc, collection, deleteDoc, doc, getDoc, onSnapshot, updateDoc } from 'firebase/firestore'
import { Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react'
import { auth, db } from '../lib/firebase'

type Customer={id:string;name:string;phone:string;address:string;location?:string;notes?:string}
const empty={name:'',phone:'',address:'',location:'',notes:''}

export default function Customers(){
 const [role,setRole]=useState(''),[items,setItems]=useState<Customer[]>([]),[search,setSearch]=useState(''),[form,setForm]=useState(empty),[editing,setEditing]=useState<string|null>(null),[open,setOpen]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!db||!auth.currentUser)return;getDoc(doc(db,'users',auth.currentUser.uid)).then(s=>setRole(s.data()?.role??'')).catch(()=>setError('Unable to load your profile.'))},[])
 useEffect(()=>{if(!db)return;return onSnapshot(collection(db,'customers'),s=>setItems(s.docs.map(d=>({id:d.id,...d.data()} as Customer))),()=>setError('Unable to load customers.'))},[])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(c=>!q||[c.name,c.phone,c.address,c.location].some(v=>v?.toLowerCase().includes(q)))},[items,search])
 function start(c?:Customer){setEditing(c?.id??null);setForm(c?{name:c.name,phone:c.phone,address:c.address,location:c.location??'',notes:c.notes??''}:empty);setOpen(true);setError('')}
 async function save(e:React.FormEvent){e.preventDefault();if(!db||!auth.currentUser||!form.name.trim()){setError('Customer name is required.');return}try{const data={name:form.name.trim(),phone:form.phone.trim(),address:form.address.trim(),location:form.location.trim(),notes:form.notes.trim(),updatedAt:new Date().toISOString()};if(editing)await updateDoc(doc(db,'customers',editing),data);else await addDoc(collection(db,'customers'),{...data,createdAt:new Date().toISOString()});setOpen(false)}catch{setError('Could not save customer.')}}
 async function remove(id:string){if(!db||!confirm('Delete this customer?'))return;try{await deleteDoc(doc(db,'customers',id))}catch{setError('Only the owner can delete customers.')}}
 return <section className="page-section"><div className="section-heading"><div><p className="eyebrow">Customer book</p><h2>Customers</h2><p className="muted">{items.length} customer{items.length===1?'':'s'} recorded.</p></div><button type="button" className="primary-button compact" onClick={()=>start()}><Plus size={17}/>Add customer</button></div>{error&&<div className="notice">{error}</div>}<div className="search-box"><Search size={18}/><input aria-label="Search customers" placeholder="Search name, phone or address" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="customer-grid">{filtered.map(c=><article className="customer-card" key={c.id}><div className="customer-icon"><Users size={21}/></div><div className="customer-body"><h3>{c.name}</h3><p>{c.phone||'No phone number'}</p><p>{c.address||'No address recorded'}</p>{c.location&&<p>{c.location}</p>}{c.notes&&<p className="muted">{c.notes}</p>}</div><div className="card-actions"><button type="button" onClick={()=>start(c)} aria-label={'Edit '+c.name}><Pencil size={14}/>Edit</button>{role==='owner'&&<button type="button" onClick={()=>remove(c.id)} aria-label={'Delete '+c.name}><Trash2 size={14}/>Delete</button>}</div></article>)}</div>{filtered.length===0&&<div className="page-card empty-state"><Users size={28}/><h3>No customers found</h3><p className="muted">{search?'Try another search.':'Add the first customer to start building delivery history.'}</p></div>}{open&&<div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-heading"><div><p className="eyebrow">{editing?'Edit':'New'} customer</p><h3>Customer details</h3></div><button type="button" className="close-button" onClick={()=>setOpen(false)} aria-label="Close"><X/></button></div><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="form-row"><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div><label>Address<textarea rows={2} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Notes<textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary-button" type="submit">{editing?'Save changes':'Add customer'}</button></form></div>}</section>
}