import { useEffect, useMemo, useState } from 'react'
import { addDoc, collection, deleteDoc, doc, getDoc, onSnapshot, query, where } from 'firebase/firestore'
import { Fuel as FuelIcon, Plus, Trash2 } from 'lucide-react'
import { auth, db } from '../lib/firebase'

type Truck={id:string;registrationNumber?:string;make?:string;model?:string;driverId?:string;status?:string}
type FuelRecord={id:string;truckId:string;litres:number;amount:number;odometer:number;station:string;date:string;createdBy?:string}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export default function Fuel(){
 const [trucks,setTrucks]=useState<Truck[]>([]),[records,setRecords]=useState<FuelRecord[]>([]),[role,setRole]=useState(''),[assigned,setAssigned]=useState(''),[form,setForm]=useState({truckId:'',litres:'',amount:'',odometer:'',station:'',date:today()}),[error,setError]=useState('')
 useEffect(()=>{if(!db||!auth.currentUser)return;getDoc(doc(db,'users',auth.currentUser.uid)).then(p=>{setRole(p.data()?.role??'');setAssigned(p.data()?.assignedTruckId??'')}).catch(()=>setError('Unable to load your profile.'))},[])
 useEffect(()=>{if(!db)return;return onSnapshot(collection(db,'trucks'),s=>setTrucks(s.docs.map(d=>({id:d.id,...d.data()} as Truck))),()=>setError('Unable to load trucks.'))},[])
 useEffect(()=>{if(!db||!auth.currentUser||!role)return;const q=role==='owner'?collection(db,'fuelRecords'):assigned?query(collection(db,'fuelRecords'),where('truckId','==',assigned)):null;if(!q){setRecords([]);return}return onSnapshot(q,s=>setRecords(s.docs.map(d=>({id:d.id,...d.data()} as FuelRecord)).sort((a,b)=>b.date.localeCompare(a.date))),()=>setError('Unable to load fuel records.'))},[role,assigned])
 const usable=role==='owner'?trucks:trucks.filter(t=>t.id===assigned)
 useEffect(()=>{if(role==='driver'&&assigned)setForm(f=>({...f,truckId:assigned}))},[role,assigned])
 const totalLitres=useMemo(()=>records.reduce((s,r)=>s+Math.max(0,Number(r.litres)||0),0),[records]),totalSpend=useMemo(()=>records.reduce((s,r)=>s+Math.max(0,Number(r.amount)||0),0),[records])
 async function save(e:React.FormEvent){e.preventDefault();if(!db||!auth.currentUser||!form.truckId||Number(form.litres)<=0||Number(form.amount)<0||Number(form.odometer)<0||!form.date){setError('Please enter a truck, positive litres, amount, date and odometer.');return}if(role==='driver'&&form.truckId!==assigned){setError('You can only record fuel for your assigned truck.');return}try{await addDoc(collection(db,'fuelRecords'),{truckId:form.truckId,litres:Number(form.litres),amount:Number(form.amount),odometer:Number(form.odometer),station:form.station.trim(),date:form.date,createdBy:auth.currentUser.uid,createdAt:new Date().toISOString()});setForm(f=>({...f,litres:'',amount:'',odometer:'',station:''}));setError('')}catch{setError('Could not save fuel record.')}}
 async function remove(id:string){if(role!=='owner'||!db||!confirm('Delete this fuel record?'))return;try{await deleteDoc(doc(db,'fuelRecords',id))}catch{setError('Could not delete fuel record.')}}
 const truckName=(id:string)=>{const t=trucks.find(x=>x.id===id);return t?.registrationNumber||`${t?.make||'TATA'} ${t?.model||'1518'}`}
 return <section className="page-section"><div className="section-heading"><div><p className="eyebrow">Fuel log</p><h2>Fuel</h2><p className="muted">Track fuel usage, costs and odometer readings.</p></div><button type="button" className="primary-button compact" onClick={()=>setForm(f=>({...f,truckId:role==='driver'?assigned:(trucks.find(t=>t.status==='active')?.id||'')}))}><Plus size={17}/>Add fuel</button></div>{error&&<div className="notice">{error}</div>}<div className="fuel-stats"><div className="stat"><span>Total litres shown</span><strong>{totalLitres.toLocaleString('en-ZA',{maximumFractionDigits:1})} L</strong></div><div className="stat"><span>Fuel spend shown</span><strong>R{totalSpend.toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong></div></div><div className="page-card"><form className="fuel-form" onSubmit={save}><div className="form-row"><label>Truck<select required disabled={role==='driver'} value={form.truckId} onChange={e=>setForm({...form,truckId:e.target.value})}><option value="">Select truck</option>{usable.map(t=><option key={t.id} value={t.id}>{t.registrationNumber||t.id}</option>)}</select></label><label>Date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><div className="form-row"><label>Litres<input type="number" min="0.1" step="0.1" required value={form.litres} onChange={e=>setForm({...form,litres:e.target.value})}/></label><label>Amount (R)<input type="number" min="0" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label></div><div className="form-row"><label>Odometer (km)<input type="number" min="0" step="1" required value={form.odometer} onChange={e=>setForm({...form,odometer:e.target.value})}/></label><label>Station<input value={form.station} onChange={e=>setForm({...form,station:e.target.value})}/></label></div><button className="primary-button" type="submit"><FuelIcon size={17}/>Save fuel record</button></form></div><div className="page-card"><p className="eyebrow">Recent records</p><div className="fuel-list">{records.map(r=><div className="fuel-row" key={r.id}><div><strong>{truckName(r.truckId)}</strong><span>{r.date} · {r.litres} L · {Number(r.odometer).toLocaleString('en-ZA')} km{r.station?' · '+r.station:''}</span></div><div className="fuel-row-end"><strong>R{Number(r.amount).toLocaleString('en-ZA',{minimumFractionDigits:2})}</strong>{role==='owner'&&<button type="button" className="icon-button danger" onClick={()=>remove(r.id)} aria-label="Delete fuel record"><Trash2 size={15}/></button>}</div></div>)}</div>{records.length===0&&<p className="muted">No fuel records yet.</p>}</div></section>
}