import { useEffect, useState } from 'react'
import { addDoc, collection, doc, getDoc, onSnapshot, query, where, updateDoc } from 'firebase/firestore'
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage'
import { CheckCircle2, ClipboardCheck, MapPin, Navigation, PackageCheck, Camera, Send } from 'lucide-react'
import { auth, db, storage } from '../lib/firebase'

type Truck={id:string;registrationNumber?:string;driverId?:string;status?:string;currentOdometer?:number}
type Delivery={id:string;customerName?:string;customerId?:string;truckId?:string;driverId?:string;driverName?:string;deliveryStatus?:string;deliveryDate?:string;notes?:string;price?:number}
type Inspection={id:string;truckId:string;driverId:string;date:string;checks:Record<string,boolean>;notes?:string}
const checks=['Tyres','Brakes','Engine oil','Coolant','Lights','Indicators','Horn','Tipper body','Mirrors','Leaks']
function localDate(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}

export default function Operations(){
 const [role,setRole]=useState<'owner'|'driver'|null>(null),[truck,setTruck]=useState<Truck|null>(null),[trucks,setTrucks]=useState<Truck[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[inspections,setInspections]=useState<Inspection[]>([])
 const [selectedTruck,setSelectedTruck]=useState(''),[selectedDelivery,setSelectedDelivery]=useState(''),[locationStatus,setLocationStatus]=useState('Location sharing is off'),[message,setMessage]=useState('')
 const [checksState,setChecksState]=useState<Record<string,boolean>>({}),[notes,setNotes]=useState(''),[photo,setPhoto]=useState<File|null>(null)
 useEffect(()=>{async function load(){if(!db||!auth?.currentUser)return;const s=await getDoc(doc(db,'users',auth.currentUser.uid));if(s.exists())setRole(s.data().role)}load()},[])
 useEffect(()=>{if(!db||!auth?.currentUser||!role)return;const uid=auth.currentUser.uid;const unsubTrucks=onSnapshot(collection(db,'trucks'),s=>{const list=s.docs.map(d=>({id:d.id,...d.data()} as Truck));setTrucks(list);if(role==='driver'){const mine=list.find(t=>t.driverId===uid);setTruck(mine||null);setSelectedTruck(mine?.id||'')}else if(selectedTruck){setTruck(list.find(t=>t.id===selectedTruck)||null)}else setTruck(list[0]||null)},()=>setMessage('Unable to load trucks.'));const unsubDeliveries=onSnapshot(role==='driver'?query(collection(db,'deliveries'),where('driverId','==',uid)):collection(db,'deliveries'),s=>setDeliveries(s.docs.map(d=>({id:d.id,...d.data()} as Delivery)).filter(d=>d.deliveryStatus!=='delivered')),()=>setMessage('Unable to load active deliveries.'));const unsubInspections=onSnapshot(query(collection(db,'inspections'),where('driverId','==',uid)),s=>setInspections(s.docs.map(d=>({id:d.id,...d.data()} as Inspection))),()=>setMessage('Unable to load inspections.'));return()=>{unsubTrucks();unsubDeliveries();unsubInspections()}},[role,selectedTruck])
 async function saveInspection(e:React.FormEvent){e.preventDefault();if(!db||!auth?.currentUser||!truck){setMessage('Select or assign a truck first.');return}if(Object.values(checksState).some(v=>!v)){setMessage('Please confirm every inspection item before saving.');return}try{await addDoc(collection(db,'inspections'),{truckId:truck.id,driverId:auth.currentUser.uid,date:localDate(),checks:checksState,notes:notes.trim(),createdAt:new Date().toISOString()});setMessage('Daily inspection saved.')}catch{setMessage('Could not save the inspection. Check your permissions.')}}
 async function updateDeliveryStatus(status:'on_the_way'|'delivered'){if(!db||!selectedDelivery)return;try{await updateDoc(doc(db,'deliveries',selectedDelivery),{deliveryStatus:status,...(status==='delivered'?{deliveryDate:localDate()}:{}),updatedAt:new Date().toISOString()});setMessage(status==='delivered'?'Delivery marked as delivered.':'Delivery started.')}catch{setMessage('Could not update the delivery.')}}
 function shareLocation(){if(!navigator.geolocation){setLocationStatus('This phone does not support location sharing.');return}setLocationStatus('Requesting location permission…');navigator.geolocation.getCurrentPosition(async p=>{const link='https://www.google.com/maps?q='+p.coords.latitude+','+p.coords.longitude;try{await navigator.clipboard.writeText(link);setLocationStatus('Location link copied. Send it to the customer or owner.')}catch{setLocationStatus(link)}},()=>setLocationStatus('Location permission was denied or unavailable.'),{enableHighAccuracy:true,timeout:10000})}
 async function uploadProof(){if(!storage||!db||!selectedDelivery||!photo||!auth?.currentUser){setMessage('Choose a delivery and photo first.');return}try{const path='deliveryProof/'+selectedDelivery+'/'+Date.now()+'-'+photo.name.replace(/[^a-zA-Z0-9._-]/g,'_');const storageRef=ref(storage,path);await uploadBytes(storageRef,photo);const url=await getDownloadURL(storageRef);await updateDoc(doc(db,'deliveries',selectedDelivery),{proofUrl:url,proofUploadedAt:new Date().toISOString(),proofUploadedBy:auth.currentUser.uid,updatedAt:new Date().toISOString()});setPhoto(null);setMessage('Delivery proof uploaded.')}catch{setMessage('Could not upload delivery proof. Check Firebase Storage configuration.')}}
 const inspectionToday=inspections.some(i=>i.date===localDate()&&i.truckId===truck?.id)
 return <section className="page-section">
  <div className="section-heading"><div><p className="eyebrow">Day-to-day work</p><h2>Operations</h2><p className="muted">A simple workflow for inspections, deliveries and location sharing.</p></div></div>
  {message&&<div className="notice">{message}</div>}
  {role==='owner'&&<div className="page-card"><p className="eyebrow">Truck</p><h3>Choose a truck</h3><select value={selectedTruck} onChange={e=>setSelectedTruck(e.target.value)}><option value="">Select truck</option>{trucks.map(t=><option key={t.id} value={t.id}>{t.registrationNumber||t.id}</option>)}</select><p className="muted">Drivers automatically use their assigned truck.</p></div>}
  <div className="operations-grid">
   <div className="page-card"><div className="operation-title"><ClipboardCheck size={22}/><div><p className="eyebrow">Safety</p><h3>Daily inspection</h3></div></div><p className="muted">{truck?(truck.registrationNumber||'Truck')+' · '+Number(truck.currentOdometer||0).toLocaleString('en-ZA')+' km':'No truck assigned.'}</p>{inspectionToday?<div className="success-box"><CheckCircle2 size={18}/> Inspection completed today.</div>:<form onSubmit={saveInspection} className="checklist">{checks.map(item=><label key={item}><input type="checkbox" checked={!!checksState[item]} onChange={e=>setChecksState({...checksState,[item]:e.target.checked})}/><span>{item}</span></label>)}<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Problems or notes (optional)"/><button className="primary-button" type="submit">Save inspection</button></form>}</div>
   <div className="page-card"><div className="operation-title"><PackageCheck size={22}/><div><p className="eyebrow">Deliveries</p><h3>Driver workflow</h3></div></div>{deliveries.length===0?<p className="muted">No active deliveries assigned.</p>:<><select value={selectedDelivery} onChange={e=>setSelectedDelivery(e.target.value)}><option value="">Select delivery</option>{deliveries.map(d=><option key={d.id} value={d.id}>{d.customerName||'Customer'} · {d.deliveryStatus||'pending'}</option>)}</select><div className="operation-actions"><button type="button" className="secondary-button" disabled={!selectedDelivery} onClick={()=>updateDeliveryStatus('on_the_way')}><Navigation size={16}/> On the way</button><button type="button" className="primary-button" disabled={!selectedDelivery} onClick={()=>updateDeliveryStatus('delivered')}><CheckCircle2 size={16}/> Delivered</button></div><label className="upload-field">Proof photo<input type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)}/></label><button type="button" className="secondary-button" disabled={!photo||!selectedDelivery} onClick={uploadProof}><Camera size={16}/> Upload proof</button></>}</div>
   <div className="page-card"><div className="operation-title"><MapPin size={22}/><div><p className="eyebrow">Location</p><h3>Share current location</h3></div></div><p className="muted">Uses the driver's phone location only when the button is pressed. No dedicated GPS device is required.</p><button className="primary-button" onClick={shareLocation}><Send size={16}/> Copy location link</button><div className="location-status">{locationStatus}</div></div>
  </div>
 </section>
}
